#!/bin/bash

# Function to display information about a subdomain
display_subdomain_info() {
    subdomain=$1
    domain=$2
    record_type=$(dig +short $subdomain.$domain | awk '{ if (NR == 1) { print $1 }}')
    destination=$(dig +short $subdomain.$domain | awk '{ if (NR == 1) { print $2 }}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main function
main() {
    domain=$1
    subdomain=$2
    
    if [ -z "$subdomain" ]; then
        display_subdomain_info "www" $domain
        display_subdomain_info "lb-01" $domain
        display_subdomain_info "web-01" $domain
        display_subdomain_info "web-02" $domain
    else
        display_subdomain_info $subdomain $domain
    fi
}

# Check for correct number of arguments
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

main "$@"

